/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wifi.tickets;

import java.awt.Color;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import org.jfree.chart.ChartUtilities;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.labels.PieSectionLabelGenerator;
import org.jfree.chart.labels.StandardPieSectionLabelGenerator;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.plot.PiePlot3D;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author ACER-PC
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GenTicket = new javax.swing.JButton();
        RegistroUsu = new javax.swing.JButton();
        RegistroVenta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        CambioContra = new javax.swing.JButton();
        Planes = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Panel principal");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("2.png")).getImage());

        GenTicket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wifi/tickets/icons/user-add-icon.png"))); // NOI18N
        GenTicket.setText("Generar ticket");
        GenTicket.setMaximumSize(new java.awt.Dimension(157, 41));
        GenTicket.setMinimumSize(new java.awt.Dimension(157, 41));
        GenTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenTicketActionPerformed(evt);
            }
        });

        RegistroUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wifi/tickets/icons/User-Group-icon.png"))); // NOI18N
        RegistroUsu.setText("Registro de tickets");
        RegistroUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroUsuActionPerformed(evt);
            }
        });

        RegistroVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wifi/tickets/icons/Money-Graph-icon.png"))); // NOI18N
        RegistroVenta.setText("Registro de ventas");
        RegistroVenta.setMaximumSize(new java.awt.Dimension(157, 41));
        RegistroVenta.setMinimumSize(new java.awt.Dimension(157, 41));
        RegistroVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroVentaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wifi/tickets/icons/Network-Panel-Settings-icon.png"))); // NOI18N
        jLabel1.setText("Panel principal");

        CambioContra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wifi/tickets/icons/Key-icon.png"))); // NOI18N
        CambioContra.setText("Cambiar contraseña");
        CambioContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CambioContraActionPerformed(evt);
            }
        });

        Planes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wifi/tickets/icons/Money-icon.png"))); // NOI18N
        Planes.setText("Planes y precios");
        Planes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlanesActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 177, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Planes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RegistroUsu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CambioContra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(GenTicket, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RegistroVenta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(GenTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(RegistroVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(RegistroUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Planes, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CambioContra, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void GenTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenTicketActionPerformed
        this.setVisible(false);
        new Tickets().setVisible(true);
    }//GEN-LAST:event_GenTicketActionPerformed

    private void RegistroVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroVentaActionPerformed
        this.setVisible(false);
        new Ventas().setVisible(true);
    }//GEN-LAST:event_RegistroVentaActionPerformed

    private void CambioContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CambioContraActionPerformed
        this.setVisible(false);
        new CambioContra().setVisible(true);
    }//GEN-LAST:event_CambioContraActionPerformed

    private void RegistroUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroUsuActionPerformed
        this.setVisible(false);
        new RegistroUsu().main();
    }//GEN-LAST:event_RegistroUsuActionPerformed

    private void PlanesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlanesActionPerformed
        this.setVisible(false);
        new Planes().setVisible(true);
    }//GEN-LAST:event_PlanesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String... args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);

                try {
                    Connection conn = DbConnect.getConnection();
                    PreparedStatement pst = (PreparedStatement) conn.prepareStatement("SELECT Mes, sum(Precio) as total FROM tickets GROUP BY Mes");
                    ResultSet rs = pst.executeQuery();
                    DefaultPieDataset dataset = new DefaultPieDataset();
                    while (rs.next()) {
                        dataset.setValue(
                                rs.getString("Mes"),
                                Double.parseDouble(rs.getString("total")));
                    }
                    JFreeChart chart = ChartFactory.createPieChart(
                            "Ventas mensuales", // chart title           
                            dataset, // data           
                            true, // include legend          
                            true,
                            true);
                    chart.setBackgroundPaint(new Color(240, 240, 240));
                    final PiePlot plot = (PiePlot) chart.getPlot();
                    PieSectionLabelGenerator labelGenerator = new StandardPieSectionLabelGenerator("{0}={1}",
                            new DecimalFormat("$#,##0 COP"),
                            NumberFormat.getPercentInstance());
                    plot.setLabelGenerator(labelGenerator);
                    plot.setCircular(true);
                    plot.setSimpleLabels(true);
                    plot.setNoDataMessage("No hay datos disponibles");

                    final ChartPanel chartPanel = new ChartPanel(chart);
                    jPanel1.add(chartPanel);

                } catch (Exception e) {
                    e.printStackTrace();

                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CambioContra;
    private javax.swing.JButton GenTicket;
    private javax.swing.JButton Planes;
    private javax.swing.JButton RegistroUsu;
    private javax.swing.JButton RegistroVenta;
    private javax.swing.JLabel jLabel1;
    private static javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
